Node notes cli
michael5522/m2-0522-code-solutions pull request #23
Opened 2022-06-29 04:20 UTC by michael5522

![Screen Shot 2022-06-28 at 9 19 18 PM](https://user-images.githubusercontent.com/55678486/176350831-823c596a-1359-4af3-9c32-6331ca8bfc94.png)

2022-06-29 17:53 UTC, TimelikeClosure requested changes

2022-06-29 17:53 UTC, TimelikeClosure commented on node-notes-cli/app.js
> +}
The update operation should only be able to modify existing notes, not create new ones.

2022-07-01 03:27 UTC, michael5522 commented
![Screen Shot 2022-06-30 at 8 25 17 PM](https://user-images.githubusercontent.com/55678486/176817673-ffc7b93a-1ebf-4aaf-9047-a2989653e4b3.png)
made sure that the number exists before updating

2022-07-01 03:28 UTC, TimelikeClosure approved these changes

2022-07-01 03:53 UTC, merged