Javascript-constructors- Michael Chang
michael5522/m2-0522-code-solutions pull request #4
Opened 2022-05-12 22:59 UTC by michael5522

<img width="563" alt="Screen Shot 2022-05-12 at 3 56 54 PM" src="https://user-images.githubusercontent.com/55678486/168180802-b9dd44d1-d441-4e41-a758-3fbce235f179.png">
<img width="822" alt="Screen Shot 2022-05-12 at 3 36 38 PM" src="https://user-images.githubusercontent.com/55678486/168180804-af04163c-8b06-4586-b6be-e7307b663b74.png">
<img width="807" alt="Screen Shot 2022-05-12 at 3 36 13 PM" src="https://user-images.githubusercontent.com/55678486/168180807-38d282c5-0a87-4ce7-8f60-b3f4885e3c7d.png">

2022-05-13 00:29 UTC, TimelikeClosure requested changes

2022-05-13 00:29 UTC, TimelikeClosure commented on javascript-constructors/student.js
> +/* exported Student */
Please complete the `Student` constructor definition.

2022-05-16 22:41 UTC, michael5522 commented
![Screen Shot 2022-05-16 at 3 38 39 PM](https://user-images.githubusercontent.com/55678486/168693987-70e2e739-454a-4003-910a-6e2f48ceb959.png)

2022-05-17 01:05 UTC, TimelikeClosure approved these changes

2022-05-17 01:27 UTC, merged