Javascript carousel - Michael Chang
michael5522/m2-0522-code-solutions pull request #7
Opened 2022-05-18 04:03 UTC by michael5522

https://user-images.githubusercontent.com/55678486/168954810-f723cb03-7540-4214-b58e-1acef4d8e5be.mov

https://user-images.githubusercontent.com/55678486/168954818-a06746fb-be56-4ced-9682-af4cc5a36ceb.mov

https://user-images.githubusercontent.com/55678486/168954819-ed8ac896-906f-4181-a8b6-5a54d4ce5754.mov

2022-05-18 04:12 UTC, TimelikeClosure requested changes

2022-05-18 04:12 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +  }
That's a _lot_ of repetition: try to combine these.

2022-05-18 04:12 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +setInterval(changeSlide, 3000);
The interval should restart every time the user interacts with the carousel controls.

2022-05-18 04:12 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +  backButtonAll[i].addEventListener('click', function (event) {
The forward and back buttons should only have one listener apiece, not 5.

2022-05-19 05:25 UTC, michael5522 commented
https://user-images.githubusercontent.com/55678486/169216548-8c83eb5e-451d-40a9-bf30-e9b341f6d635.mov


https://user-images.githubusercontent.com/55678486/169216567-66cf6f3c-590f-4f28-aeaa-fa438aeae029.mov


https://user-images.githubusercontent.com/55678486/169216578-2ce80f98-95ff-42e7-8a98-44b278ab7990.mov

2022-05-20 01:33 UTC, TimelikeClosure requested changes

2022-05-20 01:33 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +  backButtonAll[i].addEventListener('click', function (event) {
This still needs to be addressed.

2022-05-20 01:47 UTC, TimelikeClosure approved these changes

2022-05-20 01:50 UTC, merged